version: "3.8"
services:
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.proxy
    command: sh -c "/usr/wait-for-it.sh nginx:80 -t 30 && /usr/wait-for-it.sh frontend:80 -t 30 && nginx -g \"daemon off;\""
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./deployment/config/proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - nginx

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: dev
    command: sh -c "/usr/wait-for-it.sh nginx:80 -t 60 && npm run serve"
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/src
    environment:
      - NODE_ENV=local
    depends_on:
      - nginx

  api:
    build:
      args:
        user: martin
        uid: 1000
      context: .
      dockerfile: ./api/Dockerfile
      target: api
    command: sh -c "/usr/src/wait-for-it.sh mysql:3306 -t 30 && /usr/src/wait-for-it.sh redis:6379 -t 30 && php-fpm"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "9000" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - ./api/composer.json:/usr/src/composer.json
      - ./api/composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
      - ./deployment/config/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - update
      - mysql
      - redis

  scheduler:
    build:
      args:
          user: martin
          uid: 1000
      context: .
      dockerfile: ./api/Dockerfile
      target: scheduler
    command: sh -c "/usr/src/wait-for-it.sh mysql:3306 -t 30 && /usr/src/wait-for-it.sh redis:6379 -t 30 && sleep 60 && /usr/src/scheduler.sh"
    restart: unless-stopped
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - ./api/composer.json:/usr/src/composer.json
      - ./api/composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
      - ./api/scheduler.sh:/usr/src/scheduler.sh
    depends_on:
      - update
      - mysql
      - redis

  worker:
    build:
      args:
        user: martin
        uid: 1000
      context: .
      dockerfile: ./api/Dockerfile
      target: worker
    command: sh -c "/usr/src/wait-for-it.sh mysql:3306 -t 30 && /usr/src/wait-for-it.sh redis:6379 -t 30 && /usr/src/worker.sh"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "php", "/usr/src/artisan", "queue:monitor", "default" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - ./api/composer.json:/usr/src/composer.json
      - ./api/composer.lock:/usr/src/composer.lock
      - ./.env:/usr/src/.env
      - ./api/worker.sh:/usr/src/worker.sh
    depends_on:
      - update
      - mysql
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: unless-stopped
    command: sh -c "/usr/src/wait-for-it.sh api:9000 -t 30 && nginx -g \"daemon off;\""
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/api/health-check" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./api/composer.json:/usr/src/composer.json
      - ./api/composer.lock:/usr/src/composer.lock
      - ./api:/usr/src
      - ./deployment/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  mysql:
    build:
      args:
        password: ${DB_PASSWORD}
      context: .
      dockerfile: ./Dockerfile.mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./redisdata:/data
    ports:
      - "63790:6379"

  update:
    build:
      args:
        user: martin
        uid: 1000
      context: .
      dockerfile: ./api/Dockerfile
    command: sh -c "/usr/src/wait-for-it.sh mysql:3306 -t 30 && /usr/src/wait-for-it.sh redis:6379 -t 30 && /usr/src/update.sh"
    restart: no
    volumes:
      - ./.env:/usr/src/.env
      - ./deployment/bin/update.sh:/usr/src/update.sh
    depends_on:
      - mysql
      - redis
