name: 'Build proxy'
description: 'Build proxy image'
inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub access token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - run: |
        docker build -t $PROXY_IMAGE -f ./Dockerfile.proxy .
        docker push $PROXY_IMAGE
      shell: bash
