apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: health-check
spec:
  selector:
    matchLabels:
      name: health-check
  template:
    metadata:
      labels:
        name: health-check
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: health-check
          image: martinjoo/posts-health-check:$IMAGE_TAG
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          envFrom:
            - configMapRef:
                name: posts
            - secretRef:
                name: posts
      terminationGracePeriodSeconds: 30
