name: 'Build MySQL'
description: 'Build MySQL image'
inputs:
  dockerhub-username:
    description: 'DockerHub username'
    required: true
  dockerhub-token:
    description: 'DockerHub access token'
    required: true
  db-password:
    description: 'Database password'
    required: true

runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    - run: docker build -t $MYSQL_IMAGE --build-arg password=${{ inputs.db-password }} -f ./Dockerfile.mysql .
      shell: bash
    - run: docker push $MYSQL_IMAGE
      shell: bash
