apiVersion: v1
kind: ConfigMap
metadata:
  name: posts
data:
  IMAGE_TAG: "$IMAGE_TAG"
  APP_NAME: "posts"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "$APP_URL"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "error"

  QUEUE_CONNECTION: "redis"

  MAIL_MAILER: "log"

  AWS_BUCKET: "devops-with-laravel-storage"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  AWS_URL: "https://devops-with-laravel-storage.s3.us-east-1.amazonaws.com/"

  FILESYSTEM_DISK: "s3"

  CACHE_DRIVER: "redis"
