apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: posts-staging
spec:
  acme:
    email: m4rt1n.j00@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: posts-staging-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: posts-production
spec:
  acme:
    email: m4rt1n.j00@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: posts-production-key
    solvers:
      - http01:
          ingress:
            class: nginx
